name: build and upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create Cache Directory
        run: mkdir -p ~/cache

      - name: Cache Directory
        id: cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/cache
          key: cache-${{ runner.os }}

      - name: Pull Docker Image
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker pull paperist/texlive-ja:latest
          docker save -o ~/cache/texlive.tar paperist/texlive-ja:latest

      - name: Load Docker Image
        if: steps.cache.outputs.cache-hit == 'true'
        run: docker load -i ~/cache/texlive.tar

      - name: Build LaTeX
        run: make build

      - name: Upload PDF
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts
          path: |
            ./build/sample.pdf
            sample.tex
            sample.bib

      # -----
      # If you are pushing to GCP, please uncomment after setting the appropriate secrets.

      # - name: auth gcp
      #   uses: 'google-github-actions/auth@v1'
      #   with:
      #     workload_identity_provider: 'projects/${{ secrets.ProjectID }}/locations/global/workloadIdentityPools/${{ secrets.PoolID }}/providers/${{ secrets.ProviderName }}'
      #     service_account: '${{ secrets.ServiceAccount }}@${{ secrets.ProjectNumber }}.iam.gserviceaccount.com'

      # - name: Use gcloud CLI
      #   run: 'gcloud storage cp -r ./artifacts gs://${{ secrets.BucketsName }}'

