name: reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  reviewdog-check:
    name: reviewdog (check)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: setup reviewdog
        uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f # v1.5.0
        with:
          reviewdog_version: latest

      - name: Set up node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20

      - name: install Dependencies
        run: npm ci

      - name: Execute textlint
        run: npx textlint -f checkstyle sample.tex | reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
